// File generated by FlutterFire CLI.
// Project: alex-pos (dimeincltd@gmail.com)
// To regenerate / add more platforms:
//   dart pub global run flutterfire_cli:flutterfire configure \
//       --project=alex-pos --platforms=android,ios
// Cloud sync is purely additive: if any platform here still throws
// (e.g. iOS not configured), FirebaseInit catches it and the app keeps
// working fully offline with LAN / Wi-Fi Direct sync intact.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  const DefaultFirebaseOptions._();

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web. '
        'Run `flutterfire configure --platforms=web` to regenerate '
        'lib/firebase_options.dart.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios. '
          'Run `flutterfire configure --platforms=ios` to regenerate '
          'lib/firebase_options.dart.',
        );
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for '
          '$defaultTargetPlatform. Run `flutterfire configure` to regenerate '
          'lib/firebase_options.dart.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkTUOGLXOR26oAuW-k_joEXAPpzkNPduA',
    appId: '1:901163093322:android:ee5ba627de3745d59085b3',
    messagingSenderId: '901163093322',
    projectId: 'alex-pos',
    storageBucket: 'alex-pos.firebasestorage.app',
  );

}